### ISSUE TITLE
Remove the Origin fork link on  poquirion/candig_compose

### ISSUE THREAD

**Issue by amanjeev** [CanDIG/candig_compose#11]
Hi @poquirion 

Not sure if it is needed, but I believe we should remove the upstream fork to your repo ( poquirion/candig_compose) from this repo. Opening a PR against this repo always shows your fork by default.

Obviously, this is true only if you are ok doing this. If you have a reason to keep the repos this way, please let me know.

**Comment by poquirion** [comment]
Yes. I will reverse the fork so this is the mother repo. I typically like to develop from my repo and do PR from there...
