### ISSUE TITLE
do you need to create a key for candig APIs or any other that use openID Connect

### ISSUE THREAD

**Issue by jimmyhli** [CanDIG/candig_compose#22]
It looks the API endpoints work fine for the ones that use openID Connect even if you delete the keys

more info to come...

**Comment by jimmyhli** [comment]
my initial conclusion is you dont - more details to come

**Comment by poquirion** [comment]
Can you provide more details about that @haoyuanli. Not sure I understand the problem.

**Comment by jimmyhli** [comment]
Sorry, my original question is

There's a step to create a key in order for an API to be functioning, do we need the key to be created for APIs that use openID connect?

**Comment by amanjeev** [comment]
@haoyuanli Was this answered to you somewhere else? Can we answer this if not but if it has been then please close this-.
