### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by amanjeev** [CanDIG/candig_compose#37]
We need to move away from racist terms like `master`. I propose `main` as a solution but I am open to other ideas. Some of our other repos are already being changed or have been changed.

I am opening this issue because I do not know yet if it may break someone's build although my belief is that it should not. 

cc/ @ljdursi , @poquirion , @haoyuanli 

PS: I had assigned it to myself but I do not have permissions. So back to your P-O.

**Comment by ljdursi** [comment]
+1 - I'd like to take this opportunity to set up some initial convention for branch names across the repos and take the have the names be meaningful for the different workflows that the repos have. E.g. trunk or main or production for those repos where it is where the feature branches come from, and a different name for e.g. candig-server where develop is the main branch and from there is merged into the production branch from which releases are minted.

**Comment by amanjeev** [comment]
Thank you, Jonathan! I vote that in this repo: 

```
`master` (rename) -> `production`
`devel` (rename) -> `develop`
default -> `develop`
```

Now that I think about it, and maybe it is an overkill, but we could just simplify this structure by using same process for all repos:

default branch -> `develop`
prod branch -> `production` 

This way all release annotated tags and release branches are cut from production but the continuous development is done by merging feature branches into develop.

This allows us to have keep-a-changelog with a running `[unreleased]` in the `develop` branch and cutting a release means explicitly adding the version before merge `develop` into `production`.

**Comment by amanjeev** [comment]
default is now `stable` and dev is `develop`. 
`devel` and `master` have been deleted for consistency.
